/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gavinandre_jnidemo_NativeLib */

#ifndef _Included_com_gavinandre_jnidemo_NativeLib
#define _Included_com_gavinandre_jnidemo_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gavinandre_jnidemo_NativeLib
 * Method:    enableCout
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gavinandre_jnidemo_NativeLib_enableCout
  (JNIEnv *, jclass);

/*
 * Class:     com_gavinandre_jnidemo_NativeLib
 * Method:    disableCout
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gavinandre_jnidemo_NativeLib_disableCout
  (JNIEnv *, jclass);

/*
 * Class:     com_gavinandre_jnidemo_NativeLib
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gavinandre_jnidemo_NativeLib_stringFromJNI
  (JNIEnv *, jclass);

/*
 * Class:     com_gavinandre_jnidemo_NativeLib
 * Method:    stringToJNI
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_gavinandre_jnidemo_NativeLib_stringToJNI
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
